# Settings #

general.import = ["âˆ¼/.config/alacritty/style/dracula.toml"]

[env]
TERM = "xterm-256color"

[window]
 padding.x = 10
 padding.y = 10
 startup_mode = "Maximized"
 title = "Alacritty"
# position = {x = 30, y = 20}
# dimensions = { columns = 180, lines = 48 }

#decorations = "Transparent"
decorations = "None"

opacity = 0.85
# blur = true

#option_as_alt = "Both"

[font]
normal.family = "MesloLGS NF"

size = 14

[cursor]
blink_interval = 750
style = "Beam"


